### ISSUE TITLE
Issue loading Ultimate Menu in YimMenu

### ISSUE THREAD

**Issue by Mangaia** [UltimateMenu/UltimateMenu#11]
Unable to load Ultimate Menu (latest release) in YimMenu : 
![image](https://github.com/L7NEG/Ultimate-Menu/assets/21020827/8215bf53-3c95-40fe-b69f-e097f6c3c1c9)

**Comment by L7NEG** [comment]
Just don't use yimmenu script yet bro I will release an update soon

**Comment by Mangaia** [comment]
Ah okay thanks! I would use kiddions, but no update yet :(

**Comment by L7NEG** [comment]
Yes bro I know you are right but you can still use kiddions along with scripts that are updated to 1.68

**Comment by L7NEG** [comment]
You are welcome bro ❤

**Comment by Mangaia** [comment]
I will try with this update to see if it will work on kiddions tomorrow, thanks!

**Comment by L7NEG** [comment]
Sure bro v18 is working with kiddion except some features I already updated and waiting to release it in v19 

You are welcome ❤
