### ISSUE TITLE
Requesting a few additions/alterations

### ISSUE THREAD

**Issue by Deadlineem** [UltimateMenu/UltimateMenu#13]
Ability to Gift Vehicles (Recovery service?) to Yourself/Others
Increase auto shop customer vehicle delivery time (the time it takes the cars to show up in your autoshop)
Heist Data Editors (Exactly like kiddions, I use the cayo one often)
Alter the Drop Menu and add the ability to toggle the options instead of having to click them.
Maybe a 1 click Benny's/Full upgrade and F1's/Full upgrade for vehicles.

**Comment by L7NEG** [comment]
Ability to Gift Vehicles (Recovery service?) to Yourself/Others And Maybe a 1 click Benny's/Full upgrade and F1's/Full upgrade for vehicles. Unfortunately Arent possible 

And For Heist Editor Is Already In Ultimate Menu Script

And Could You Please Give More Details About This Like Which Option Exactly In Ultimate Menu Script "Alter the Drop Menu and add the ability to toggle the options instead of having to click them."

And For "Increase auto shop customer vehicle delivery time (the time it takes the cars to show up in your autoshop)" Noted ✅

**Comment by Deadlineem** [comment]
@L7NEG Damn, nenyooo has the ability to do that so i figured with yim's ultimate menu it could work as well since its internal, maybe?

Heist editor IS in yimmenu's lua addon but its not as extensive as kiddions ultimate menu addon, thus i have to use both menus for one thing.

Inside the Money/RP drop section of your menu (Ultimate Money methods - Drop Methods) there are buttons for dropping action figures and such

1.  Big cash pile doesn't do anything for myself/others when used, just drops a cash rack and does nothing when collected
2.  All of the options are single click options, so instead of just toggling it and letting it run i have to click it 1000 times, which made me get an auto clicker for the task of dropping RP/Money
3.  I feel like all of the options (action figure wise) can be put on a drop rotation instead of having each individual drop, this would work like this (if possible):

Bubblegum figure -> Alien -> Impotent Rage - > space ranger -> etc. -- Then repeat the cycle.

Doing this would slim down the menu listing as well, making it a bit more clean and not take up so much screen space.

**Comment by L7NEG** [comment]
oh so ok your suggestions was on YimMenu One currently as yimmenu's lua api isnt complete as kiddions one i cant do it but if there is a clean docs on yimmenu's lua api sure i will do it fr

but for heists one i think yes i need to just redo a work on it to make it selective like this example 
![image](https://github.com/L7NEG/Ultimate-Menu/assets/88356593/3b43ec1e-47f1-4bb8-97ce-fbf962d80b88)

**Comment by L7NEG** [comment]
and for drop menu i will ask moha since he is the creator of it Noted ✅

**Comment by Deadlineem** [comment]
Precisely, probably should have mentioned that in the first post but if anyone can do it, its you guys.  Thanks for all the addons!

**Comment by L7NEG** [comment]
You Are Welcome Bro I Appreciate Your Feedbacks And I Hope You To Have A Great Day In Your Real Life <3
