### ISSUE TITLE
Vehicle Gifting

### ISSUE THREAD

**Issue by Deadlineem** [UltimateMenu/UltimateMenu#15]
I talked briefly with Yimura who told me to try it in lua since i was just going to compile my own yim menu

Found this, figured youd know more about it than myself.

`function func_270()
    local recipient = YimMenu.GetRecipientPlayer() -- Replace with the correct YimMenu function
    local local_59 = {} -- You need to define Local_59 based on your Lua environment

    if iLocal_69 == 4 or iLocal_69 == 5 then
        if not func_481(local_59) then
            local_59 = VEHICLE.CREATE_VEHICLE(local_59.f_1, local_59.f_3, local_59.f_6, true, true, false)
            VEHICLE.SET_VEHICLE_ON_GROUND_PROPERLY(local_59, 1084227584)
            VEHICLE.SET_VEHICLE_HAS_BEEN_OWNED_BY_PLAYER(local_59, 1)
            VEHICLE.SET_VEHICLE_DIRT_LEVEL(local_59, 13.0)
            VEHICLE.SET_VEHICLE_COLOURS(local_59, 157, 157)
            VEHICLE.SET_VEHICLE_EXTRA_COLOURS(local_59, 157, 5)

            -- Gift the vehicle to another player
            if recipient then
                -- Assuming you have a function to transfer ownership of the vehicle
                YimMenu.TransferVehicleOwnership(local_59, recipient) -- Replace with the correct YimMenu function
            end
        end
    else
        if not func_481(local_59) then
            local_59 = VEHICLE.CREATE_VEHICLE(local_59.f_1, local_59.f_3, local_59.f_6, true, true, false)
            VEHICLE.SET_VEHICLE_ON_GROUND_PROPERLY(local_59, 1084227584)
            VEHICLE.SET_VEHICLE_HAS_BEEN_OWNED_BY_PLAYER(local_59, 1)
            VEHICLE.SET_VEHICLE_DOORS_LOCKED(local_59, 3)
            VEHICLE.SET_VEHICLE_DIRT_LEVEL(local_59, 13.0)
            VEHICLE.SET_VEHICLE_COLOURS(local_59, 157, 157)
            VEHICLE.SET_VEHICLE_EXTRA_COLOURS(local_59, 157, 5)

            -- Gift the vehicle to another player
            if recipient then
                -- Assuming you have a function to transfer ownership of the vehicle
                YimMenu.TransferVehicleOwnership(local_59, recipient) -- Replace with the correct YimMenu function
            end
        end
    end

    VEHICLE.SET_VEHICLE_MODEL_IS_SUPPRESSED(local_59.f_1, true)
    STREAMING.SET_MODEL_AS_NO_LONGER_NEEDED(local_59.f_1)
end
`

@L7NEG

**Comment by L7NEG** [comment]
it looks interesting bro but "-- Assuming you have a function to transfer ownership of the vehicle" and "-- Assuming you have a function to transfer ownership of the vehicle" Which i think i dont have them fr

**Comment by Deadlineem** [comment]
If you could draw something up with the script above, we could probably ask Yimura about that function.  It has to be somewhere.

**Comment by L7NEG** [comment]
i think you are right bro i will do my best for it until you just try to find how we can make it work fr but for now im busy with exams i will be free after 22/1/2024

**Comment by L7NEG** [comment]
i just closed it but i just need to finish my exams bro fr
