### ISSUE TITLE
lscm rep level 1000

### ISSUE THREAD

**Issue by squeaks1811** [UltimateMenu/UltimateMenu#16]
ive done all the steps in the read me part of the lscm rep level 1000 but it doesnt seem to be changing my rep level is it broken or is there a certain way to do it?

**Comment by L7NEG** [comment]
if your level is above level 1 before you done all the steps unfortunately it wont make your lscm rep to lvl 1000 you can still by just resetting your level detailed tut on my discord server

**Comment by squeaks1811** [comment]
can i get a discord invite please
