### ISSUE TITLE
Cayo Editor

### ISSUE THREAD

**Issue by Deadlineem** [UltimateMenu/UltimateMenu#17]
Heres some more features for the cayo heist editor -- YimMenu 

`--Required Stats--

local MPX = PI
local PI = stats.get_int("MPPLY_LAST_MP_CHAR")
if PI == 0 then
	MPX = "MP0_"
else
	MPX = "MP1_"
end

FMC2020 = "fm_mission_controller_2020"
HIP = "heist_island_planning"

-- Editor Stuff
local heisteEditor = KAOS:add_tab("Heist Editor")
local cayoHeist = heisteEditor:add_tab("Cayo Perico Editor")

local MPX = PI
PI = stats.get_int("MPPLY_LAST_MP_CHAR")
if PI == 0 then
	MPX = "MP0_"
else
	MPX = "MP1_"
end

cayoHeist:add_text("Setup Heist")

cayoHeist:add_button("Panther Only (Hard)", function()
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_BS_GEN"), 131071, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_BS_ENTR"), 63, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_BS_ABIL"), 63, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_WEAPONS"), 5, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_WEP_DISRP"), 3, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_ARM_DISRP"), 3, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_HEL_DISRP"), 3, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_TARGET"), 5, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_TROJAN"), 2, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4CNF_APPROACH"), -1, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_CASH_I"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_CASH_C"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_WEED_I"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_WEED_C"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_COKE_I"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_COKE_C"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_CASH_I"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_GOLD_I"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_GOLD_C"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_PAINT"), -1, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4_PROGRESS"), 131055, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_CASH_I_SCOPED"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_CASH_C_SCOPED"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_WEED_I_SCOPED"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_WEED_C_SCOPED"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_COKE_I_SCOPED"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_COKE_C_SCOPED"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_GOLD_I_SCOPED"), 0, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_GOLD_C_SCOPED"), -3, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4LOOT_PAINT_SCOPED"), -1, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4_MISSIONS"), 65535, true)
	STATS.STAT_SET_INT(joaat(MPX .. "H4_PLAYTHROUGH_STATUS"), 32, true)
	
	gui.show_message("Cayo Heist", "Panther Hard Mode has been set up!")
	gui.show_message("Cayo Heist", "Reset the board to see the changes")
end)
cayoHeist:add_sameline()
cayoHeist:add_button("Reset Kosatka Board", function()
        locals.set_int(HIP, 1544, 2)
		gui.show_message("Cayo Heist", "Planning board has been reset!")
end)

cayoHeist:add_separator()
cayoHeist:add_text("During Heist")
cayoHeist:add_button("Skip Drainage Cut", function()
    locals.set_int(FMC2020, 29118, 6)
	gui.show_message("Cayo Heist", "Bypassed Drainage Cut")
end)
cayoHeist:add_sameline()
cayoHeist:add_button("Skip Fingerprint Scanner", function()
   locals.set_int(FMC2020, 24333, 5)
   gui.show_message("Cayo Heist", "Bypassed Fingerprint Scanner")
end)
cayoHeist:add_sameline()
cayoHeist:add_button("Skip Glass Cut", function()
    locals.set_float(FMC2020, 30357 + 3, 100.0)
	gui.show_message("Cayo Heist", "Bypassed Plasma Cutter")
end)
cayoHeist:add_separator()
cayoHeist:add_text("After Heist")
cayoHeist:add_button("Skip Cooldown", function()
	-- Solo Skip
	STATS.STAT_SET_INT(joaat("MP0_H4_TARGET_POSIX"), 1659643454, true)
	STATS.STAT_SET_INT(joaat("MP0_H4_COOLDOWN"), 0, true)
	STATS.STAT_SET_INT(joaat("MP0_H4_COOLDOWN_HARD"), 0, true)
	-- Multiplayer Skip
	STATS.STAT_SET_INT(joaat("MP0_H4_TARGET_POSIX"), 1659429119, true)
	STATS.STAT_SET_INT(joaat("MP0_H4_COOLDOWN"), 0, true)
	STATS.STAT_SET_INT(joaat("MP0_H4_COOLDOWN_HARD"), 0, true)
	-- Solo Skip (Second Character)
	STATS.STAT_SET_INT(joaat("MP1_H4_TARGET_POSIX"), 1659643454, true)
	STATS.STAT_SET_INT(joaat("MP1_H4_COOLDOWN"), 0, true)
	STATS.STAT_SET_INT(joaat("MP1_H4_COOLDOWN_HARD"), 0, true)
	-- Multiplayer Skip (Second Character)
	STATS.STAT_SET_INT(joaat("MP1_H4_TARGET_POSIX"), 1659429119, true)
	STATS.STAT_SET_INT(joaat("MP1_H4_COOLDOWN"), 0, true)
	STATS.STAT_SET_INT(joaat("MP1_H4_COOLDOWN_HARD"), 0, true)
	
	gui.show_message("Cayo Heist", "Skipped Cayo Perico Cooldown for all characters")
	gui.show_message("Cayo Heist", "Go to story mode and come back to apply the reset")
end)
cayoHeist:add_separator()
cayoHeist:add_text("How to Set Up or Bypass Cooldown:")
cayoHeist:add_text("Make sure you have completed the heist and you are standing in front of the planning screen with the option to set up the heist.")
cayoHeist:add_text("If you need to bypass the cooldown, use the bypass button, go to story mode, come back to gta online and go inside your kosatka.")
cayoHeist:add_text("Click your desired setup from the options and press Reset Kosatka Board, these options currently have NO SECONDARIES.")
cayoHeist:add_separator()
cayoHeist:add_text("How to Skip Things:")
cayoHeist:add_text("Wait for the screen to get to the point you are cutting/hacking and press the button to skip that portion.  Super easy")`

@L7NEG should let me contribute to the Yim portion.  Im learning via Yim's platform 

https://github.com/Deadlineem/Extras-Addon-for-YimMenu

**Comment by L7NEG** [comment]
sure bro + thx for your suggestions approved <3 ✅

**Comment by L7NEG** [comment]
just for the main https://github.com/L7NEG/Ultimate-Menu with the W changes you made then open a pull request when you are done ✅

**Comment by Deadlineem** [comment]
> just fork the main https://github.com/L7NEG/Ultimate-Menu with the W changes you made then open a pull request when you are done ✅

Word, im still tweaking it but i added the bag size editor and remove cctv functions as well.  All im missing for the heist now on the script is the kill buttons (a delete button would be more ideal since it wont trigger the enemies as alerted)

Once its finished ill make a PR on here.

**Comment by L7NEG** [comment]
> > just fork the main https://github.com/L7NEG/Ultimate-Menu with the W changes you made then open a pull request when you are done ✅
> 
> Word, im still tweaking it but i added the bag size editor and remove cctv functions as well. All im missing for the heist now on the script is the kill buttons (a delete button would be more ideal since it wont trigger the enemies as alerted)
> 
> Once its finished ill make a PR on here.

sure bro np i wait it + keep it up <3
