### ISSUE TITLE
Vehicle stuff

### ISSUE THREAD

**Issue by redefault** [UltimateMenu/UltimateMenu#18]
Keep car always clean [ dirt level forced to 0 when toggled]
Drift Mode [edit the values to be like the new drift tune}

Values:
[You may modify them to be faster or such]
> 
>     acceleration = 0.7;
>     gravity = 7.5;
>     mass = 1500;
>     drift_tyres_enabled = true;
>     drive_bias_front = 0.05;
>     up_shift = 20;
>     down_shift = 20;
>     steering_lock = 75;

**Comment by L7NEG** [comment]
> Keep car always clean [ dirt level forced to 0 when toggled] Drift Mode [edit the values to be like the new drift tune}
> 
> Values: [You may modify them to be faster or such]
> 
> > ```
> > acceleration = 0.7;
> > gravity = 7.5;
> > mass = 1500;
> > drift_tyres_enabled = true;
> > drive_bias_front = 0.05;
> > up_shift = 20;
> > down_shift = 20;
> > steering_lock = 75;
> > ```

Approved Thx For Your uggestionns <3 ✅
