### ISSUE TITLE
[FEATURE] Inf. Resupply for Drug Businesses

### ISSUE THREAD

**Issue by ENC4YP7ED** [UltimateMenu/UltimateMenu#30]
There were a Bug that resupplied every Drug Business that had the glitch done with. Maybe someway you cloud redo taht in the Lua Script as a passive Money Methode.

**Comment by L7NEG** [comment]
> There were a Bug that resupplied every Drug Business that had the glitch done with. Maybe someway you cloud redo taht in the Lua Script as a passive Money Methode.

would be great if you can open a pr with changes you want to be added or i will just work on adding acid lab script into ultimate money methods menu
