### ISSUE TITLE
Rig Casino Slots does not work

### ISSUE THREAD

**Issue by DawTheD** [UltimateMenu/UltimateMenu#33]
This feature isn't working for whatever reason. The slot machines (diamond mine & deity of the sun) are giving me random drops after ticking the box.

**Comment by RealDawTheD** [comment]
was being an idiot and forgot to update the lua in yim.

**Comment by L7NEG** [comment]
> was being an idiot and forgot to update the lua in yim.

oh xD but np bro

**Comment by RealDawTheD** [comment]
nevermind it doesnt work, atleast nightclub afk loop and ceo works

**Comment by L7NEG** [comment]
> nevermind it doesnt work, atleast nightclub afk loop and ceo works

Thx for letting me know I will look it up again to fix it

**Comment by L7NEG** [comment]
> > nevermind it doesnt work, atleast nightclub afk loop and ceo works
> 
> Thx for letting me know I will look it up again to fix it

Fixed And Added Air Cargo Money Method

**Comment by RealDawTheD** [comment]
hey it still doesnt work for me.

**Comment by L7NEG** [comment]
> hey it still doesnt work for me.

i know but i will soon push a fix for it mb

**Comment by RealDawTheD** [comment]
Oh cool, I forgot to mention I am using the YimModMenu version

**Comment by L7NEG** [comment]
> Oh cool, I forgot to mention I am using the YimModMenu version

oh xD np now you can redownload it from either releases or just from yimmenu folder in this repo enjoy bro <3

**Comment by L7NEG** [comment]
> Oh cool, I forgot to mention I am using the YimModMenu version

Can i close this issue as solved?

**Comment by RealDawTheD** [comment]
Sure
