### ISSUE TITLE
[Request] Port some features over from Kiddion's version to Yimmenu's version

### ISSUE THREAD

**Issue by BerBerOnGithub** [UltimateMenu/UltimateMenu#34]
For example, the reports counter isn't available in Yimmenu. I tried porting it over to the yimmenu's version privately for personal use, and it worked yesterday, but it dosen't work now.

**Comment by L7NEG** [comment]
> For example, the reports counter isn't available in Yimmenu. I tried porting it over to the yimmenu's version privately for personal use, and it worked yesterday, but it dosen't work now.

oh if you can do a pull request i can look at it and see a fix for it of course after i pull it into ultimatemenu main repo
