### ISSUE TITLE
YimMenu nightclub popularity & money not working

### ISSUE THREAD

**Issue by TheCaJlaT** [UltimateMenu/UltimateMenu#35]
Hello! The nightclub functions in YimMenu do not work
![image](https://github.com/user-attachments/assets/adf48eb9-8251-4101-8900-0e78c4d75db2)
I have enabled this checkbox, but nothing happens
![image](https://github.com/user-attachments/assets/e9ab67f0-421e-430d-bbe2-127f59cfe525)
This button also does not work
![image](https://github.com/user-attachments/assets/d3354f5e-f799-4a4c-a349-17df466d33ad)

**Comment by L7NEG** [comment]
> Hello! The nightclub functions in YimMenu do not work ![image](https://private-user-images.githubusercontent.com/66368050/358933782-adf48eb9-8251-4101-8900-0e78c4d75db2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMjIwMjgsIm5iZiI6MTcyNDAyMTcyOCwicGF0aCI6Ii82NjM2ODA1MC8zNTg5MzM3ODItYWRmNDhlYjktODI1MS00MTAxLTg5MDAtMGU3OGM0ZDc1ZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDIyNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MmQzNmFlNGMwNWZmOGI3NmVhYWIyOGZlMzYyYTVjNzFhZDhmNTlmYTc1MjA5ZmU1Njk5ZjdhMmNkZmYyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ASBRc0ncX4qAZUdk27FWGSLTEqYiYOqwmcpTortozQ) I have enabled this checkbox, but nothing happens ![image](https://private-user-images.githubusercontent.com/66368050/358933794-e9ab67f0-421e-430d-bbe2-127f59cfe525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMjIwMjgsIm5iZiI6MTcyNDAyMTcyOCwicGF0aCI6Ii82NjM2ODA1MC8zNTg5MzM3OTQtZTlhYjY3ZjAtNDIxZS00MzBkLWJiZTItMTI3ZjU5Y2ZlNTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDIyNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZjE5YjA2ODY0Zjc4ZTFkMDkwZTZhZGRiZTNjNDk1ZGIxNTBkODFiNTFjNzM2ZGVjNGI2ZDBlOGQyNmRmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFRrB5gYbK-pi-Ohy2Rx1ihdpmSGkuFsw2zBeE5dM9o) This button also does not work ![image](https://private-user-images.githubusercontent.com/66368050/358933811-d3354f5e-f799-4a4c-a349-17df466d33ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMjIwMjgsIm5iZiI6MTcyNDAyMTcyOCwicGF0aCI6Ii82NjM2ODA1MC8zNTg5MzM4MTEtZDMzNTRmNWUtZjc5OS00YTRjLWEzNDktMTdkZjQ2NmQzM2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDIyNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNjVhODYxOWI1ZmQzYTI2YzNmMDQ5MzM4YWQ0MTY3ZDE1MGVjMmUzNzQzMGMzYjBiMDFjYzcyMDJkY2Y5YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xoqr7tZrUqKVeYbHecSnjwhEsemWJOnk-aXvYr6PKgM)

Make sure you have latest file in the yimmenu folder bro because all of these issues were fixed fr
