### ISSUE TITLE
Ultimate Menu v2.3 Tab Not Appearing

### ISSUE THREAD

**Issue by collective13** [UltimateMenu/UltimateMenu#38]
v2.3 Tab seems to not appear when inserting script/refreshing Yim Menu
![image_2024-08-22_135720873](https://github.com/user-attachments/assets/b66c71ed-1ab8-454a-81bf-1724f51c4858)

**Comment by L7NEG** [comment]
> v2.3 Tab seems to not appear when inserting script/refreshing Yim Menu ![image_2024-08-22_135720873](https://private-user-images.githubusercontent.com/100049986/360438133-b66c71ed-1ab8-454a-81bf-1724f51c4858.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNDkyMTksIm5iZiI6MTcyNDM0ODkxOSwicGF0aCI6Ii8xMDAwNDk5ODYvMzYwNDM4MTMzLWI2NmM3MWVkLTFhYjgtNDU0YS04MWJmLTE3MjRmNTFjNDg1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxNzQ4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWJlMzZjYzU0NzM1OWNlOTI2ZTkwNGU3OTgwNDk4NWQ1OTU4Y2IwNmVhZmUxNjEzN2RkNDk5NWMzZGJiYjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CEf69fnKL9GDhSZfMyIrRLLd9XvShRMN5nK1kVKCC8U)

It is not a script error bro you just added the one without for yimmenu which Is kiddions Modest Menu version of UltimateMenu you can download the latest one for yimmenu from this link https://github.com/UltimateMenu/UltimateMenu/releases/tag/Ultimate_Menu_For_YimMenu_V2.3
