### ISSUE TITLE
one option in your script gived me ban in gta 

### ISSUE THREAD

**Issue by Beginner555989** [UltimateMenu/UltimateMenu#44]
hello guys you have new option about removing the reports .. i just pressed remove reports and i got ban.. thank you guys GG

**Comment by iSk1P** [comment]
The remove reports option is not even in ultimate menu script nor kiddions or yimmenu from 2 months ago how tf it is possible + it is something you have done like ceo 6 mil or just slot rigging wish is 100% bannable

**Comment by L7NEG** [comment]
As sk1p said it is fr damn

**Comment by Beginner555989** [comment]
![Screenshot (2)](https://github.com/user-attachments/assets/298253e0-e31e-40b2-b211-61f02c81b6f0)
![Screenshot (1)](https://github.com/user-attachments/assets/fa53b4ba-d066-418e-bbbc-603300b761eb)
look the version .. its now in the script ,, and i never made money on gta from the menu

**Comment by Beginner555989** [comment]
i am telling you this bcz i want u to get best rating .. and no one get ban from ur script .. anyway tnx u did a script for us fro free ...

**Comment by L7NEG** [comment]
> i am telling you this bcz i want u to get best rating .. and no one get ban from ur script .. anyway tnx u did a script for us fro free ...

oh noted ik it is in yimmenu i forgot fr to remove it thx for letting me know + detected methods rn are rig slots and ceo 6  mil

**Comment by Beginner555989** [comment]
> > i am telling you this bcz i want u to get best rating .. and no one get ban from ur script .. anyway tnx u did a script for us fro free ...
> 
> oh noted ik it is in yimmenu i forgot fr to remove it thx for letting me know + detected methods rn are rig slots and ceo 6 mil

i dont have an account hahah its banned .. do u know good webside selling gta with good price ? ^^

**Comment by king69666** [comment]
> > > i am telling you this bcz i want u to get best rating .. and no one get ban from ur script .. anyway tnx u did a script for us fro free ...
> > 
> > 
> > oh noted ik it is in yimmenu i forgot fr to remove it thx for letting me know + detected methods rn are rig slots and ceo 6 mil
> 
> i dont have an account hahah its banned .. do u know good webside selling gta with good price ? ^^

I've used G2A in the past. I can't however confirm it's rep as I've only used it once a long time ago. I don't think I had any problems though.
https://www.g2a.com/search?query=GTA%20V
