### ISSUE TITLE
Feature Request: Set Chips to 0

### ISSUE THREAD

**Issue by Nzii3** [UltimateMenu/UltimateMenu#46]
GUI Label: Set chips to 0
This would be in the casino tab and it would set your casino chips to 0. Could be used in case someone got the jackpot too many times and doesn’t want to get those chips in cash since it can get you banned or you just want to be safe not sorry about getting too much money from the casino.

**Comment by L7NEG** [comment]
> GUI Label: Set chips to 0 This would be in the casino tab and it would set your casino chips to 0. Could be used in case someone got the jackpot too many times and doesn’t want to get those chips in cash since it can get you banned or you just want to be safe not sorry about getting too much money from the casino.

if you have the main code of it you can open a pr and it will be approved asap

**Comment by Nzii3** [comment]
> > GUI Label: Set chips to 0 This would be in the casino tab and it would set your casino chips to 0. Could be used in case someone got the jackpot too many times and doesn’t want to get those chips in cash since it can get you banned or you just want to be safe not sorry about getting too much money from the casino.
> 
> if you have the main code of it you can open a pr and it will be approved asap

I don’t

**Comment by L7NEG** [comment]
> > > GUI Label: Set chips to 0 This would be in the casino tab and it would set your casino chips to 0. Could be used in case someone got the jackpot too many times and doesn’t want to get those chips in cash since it can get you banned or you just want to be safe not sorry about getting too much money from the casino.
> > 
> > 
> > if you have the main code of it you can open a pr and it will be approved asap
> 
> I don’t

its ok i will see what i can do fr
