### ISSUE TITLE
NightClub Remote Safe Loop Menu is not getting money and come up with an error

### ISSUE THREAD

**Issue by Kr1nxx** [UltimateMenu/UltimateMenu#47]
I was trying your lua for the first time and this feature doesn't work for me :(
I tried to toggle this option but the error pop up. I also tried to change delay and toggle bypass transaction error but same thing happen
![image](https://github.com/user-attachments/assets/2b70e543-bfdd-43c5-bd74-dc7c67e15bf5)
if im doing anything wrong please tell me ^^

**Comment by L7NEG** [comment]
> I was trying your lua for the first time and this feature doesn't work for me :( I tried to toggle this option but the error pop up. I also tried to change delay and toggle bypass transaction error but same thing happen ![image](https://private-user-images.githubusercontent.com/104755180/363689603-2b70e543-bfdd-43c5-bd74-dc7c67e15bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzcxNzEsIm5iZiI6MTcyNTQzNjg3MSwicGF0aCI6Ii8xMDQ3NTUxODAvMzYzNjg5NjAzLTJiNzBlNTQzLWJmZGQtNDNjNS1iZDc0LWRjN2M2N2UxNWJmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwODAxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2U5MGExNmMzZDlhNzlkMzQxZmY5ZjVhZjM2YTI0YzliOWY0ZGM2YjEyZGYwNDhlM2Q1NmU0YWRmOWFmMjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fZ_cSNCBRcTNIHQ7PQo9qx4YZUNM9LFbFp6BAy6TjF8) if im doing anything wrong please tell me ^^

its an issue in the code i will fix it once im back home

**Comment by L7NEG** [comment]
> I was trying your lua for the first time and this feature doesn't work for me :( I tried to toggle this option but the error pop up. I also tried to change delay and toggle bypass transaction error but same thing happen ![image](https://private-user-images.githubusercontent.com/104755180/363689603-2b70e543-bfdd-43c5-bd74-dc7c67e15bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NjA0MDIsIm5iZiI6MTcyNTU2MDEwMiwicGF0aCI6Ii8xMDQ3NTUxODAvMzYzNjg5NjAzLTJiNzBlNTQzLWJmZGQtNDNjNS1iZDc0LWRjN2M2N2UxNWJmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxODE1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTFiOGIzMGFhZWFhZWJjYThmOWZmZWZmZmFjYTI1YWE2MTgwZDQ5MWI0MzE2M2Q3YmExZTQ3Y2YzYWYzM2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bjQOJ0G-VPytE1yXeg_tRVi3L3Bn997_nT0WM0etpGg) if im doing anything wrong please tell me ^^

Fixed https://github.com/UltimateMenu/UltimateMenu/commit/c5dbaea207a6d481dd59c959c5fda6a654b8c794 Thx for letting me know <3
