### ISSUE TITLE
error when trying to do 300k nightclub loop

### ISSUE THREAD

**Issue by editz0726** [UltimateMenu/UltimateMenu#49]
an error pops up saying invalid data string please try again but doesnt work

**Comment by L7NEG** [comment]
> an error pops up saying invalid data string please try again but doesnt work

Could you screenshot the error message to see more details about it?

**Comment by editz0726** [comment]
i tried doing the mod again but this time the error didnt pop up just a transaction loaded bottom right but no money came througj

**Comment by editz0726** [comment]
but i believe the error that popped up last time said "invalid data string, please try again later."

**Comment by L7NEG** [comment]
> i tried doing the mod again but this time the error didnt pop up just a transaction loaded bottom right but no money came througj

send any screenrecord or screenshot so that i can see
