### ISSUE TITLE
Requesting Collaboration for Language System Integration in Script [Kiddions]

### ISSUE THREAD

**Issue by idk-pixel** [UltimateMenu/UltimateMenu#5]
Hello!

I've looked over your code in Ultimate Menu and I feel like there could be some things and we could showcase Ultimate Menu here over at [GTARadar](https://discord.gg/6grandtheftautoradar-tm-yi-864721154231894027), we are in server discovery and we have almost 8,000 members. I am a Kiddions LUA developer and I have coded around 2 scripts for them, but most of the scripts I code go on the Kiddions subreddit.

I was wondering if you would like to let me contact you and we can work on a Language System so others can easily understand while their main language is not English, because there is a lot of options within Ultimate Menu. 

Let me know by joining GTA Radar (or you can respond with your username) and we can work together.

My usernames:
Main: @whoaboutyt_real
Alt: @whoabt2

**Comment by L7NEG** [comment]
Sure sir I know gta radar is a most known community and I'm really happy to cooperation with you 
Sorry for my bad English 

My Main Username is : @L7NEG

**Comment by L7NEG** [comment]
All social media I have is my main username except for twitter / intsagram
