### ISSUE TITLE
Enable Nightclub $250/15s (Safe AFK)

### ISSUE THREAD

**Issue by Rabtos** [UltimateMenu/UltimateMenu#7]
Hey, love your Script! Using it daily.

I just wanted to say the option "Enable Nightclub $250/15s (Safe AFK)" seem not to work.
However it works with "Enable CEO Manager" ... 

So what is this second option Enable Nightclub $250/15s (Safe AFK)" ?

**Comment by L7NEG** [comment]
I Aprreciate Your Feedbacks man

The 250/15s is now 300k/1s You can download the latest release to see it and this is its tutorial 

[Remote Nightclub 300k_1s Tutorial](https://l7neg.modestmenu.vip/kneKtYXAtGHu/Remote%20Nightclub%20300k_1s%20Tutorial)

**Comment by Rabtos** [comment]
Woah, super fast reply. I will try that now.
