### ISSUE TITLE
[BUG] The menu is no longer up to date for YimMenu

### ISSUE THREAD

**Issue by pseudoname92** [UltimateMenu/UltimateMenu#8]
The menu is no longer up to date because of the new update of GTA 1.68, YimMenu is evolving, it is therefore necessary to evolve Ultimate Menu for YimMenu for GTA 1.68

**Comment by L7NEG** [comment]
Sure im working on updating it 90% done The Only Options Left Are Heists Editor and Nightclub safe afk and Ceo manager

**Comment by pseudoname92** [comment]
Thanks you very much for your work. Can you add option "Money drop" pls?

local model = joaat("p_poly_bag_01_s")
local pickup = joaat("pickup_money_security_case")
local player_id = {FillInHere}
local money_value = 2500
STREAMING::REQUEST_MODEL(model);

if (STREAMING.HAS_MODEL_LOADED(model)) then
	local coords = ENTITY.GET_ENTITY_COORDS(PLAYER.GET_PLAYER_PED_SCRIPT_INDEX(player_id), false);
	OBJECT::CREATE_AMBIENT_PICKUP(pickup, coords.x, coords.y, coords.z + 1, 0, money_value, model, false, true);
end

**Comment by 99-99itm** [comment]
> Sure im working on updating it 90% done The Only Options Left Are Heists Editor and Nightclub safe afk and Ceo manager

lovely .. to hear ,, and  ty for your work

**Comment by L7NEG** [comment]
> Thanks you very much for your work. Can you add option "Money drop" pls?
> 
> local model = joaat("p_poly_bag_01_s") local pickup = joaat("pickup_money_security_case") local player_id = {FillInHere} local money_value = 2500 STREAMING::REQUEST_MODEL(model);
> 
> if (STREAMING.HAS_MODEL_LOADED(model)) then local coords = ENTITY.GET_ENTITY_COORDS(PLAYER.GET_PLAYER_PED_SCRIPT_INDEX(player_id), false); OBJECT::CREATE_AMBIENT_PICKUP(pickup, coords.x, coords.y, coords.z + 1, 0, money_value, model, false, true); end

i added one but not like that one as kiddions is external menu and it has no support for native calling

**Comment by L7NEG** [comment]
> > Sure im working on updating it 90% done The Only Options Left Are Heists Editor and Nightclub safe afk and Ceo manager
> 
> lovely .. to hear ,, and ty for your work

you are welcome bro i appreciate it <3
